---

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    -   type: http
        port: 8090
  adminConnectors:
    -   type: http
        port: 8091

logging:
  level: INFO
  loggers:
    com.practise.lld: DEBUG
